###

GET http://localhost:5173/api/authors/ HTTP/1.1

###

GET http://127.0.0.1:3000/api/authors?get=unknown HTTP/1.1


###

POST  http://127.0.0.1:5173/api/authors/ HTTP/1.1
content-type: application/json

{
    "Id": "jerome",
    "author": "Jérôme Savajols"
}

###
GET https://happyapi.fr/api/ping HTTP/1.1

